//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a511838a-7734-4420-a07f-6d36eae3c3ce"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f1508a79-5588-4841-bfcc-e3d06b059271"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""f609f879-4093-47d7-8b36-47e39e64ed00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Position"",
                    ""type"": ""Value"",
                    ""id"": ""c07ecaa5-2546-4b2f-a4d3-046fe7814136"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""ffa90590-fc5c-49c5-8268-62b8bd7d1b00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shield"",
                    ""type"": ""Button"",
                    ""id"": ""7f1c8278-b2c2-48c9-b3d5-10fe0ab2c645"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shockwave"",
                    ""type"": ""Button"",
                    ""id"": ""e8d41172-4285-4c34-a205-dcc998660c4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fireball"",
                    ""type"": ""Button"",
                    ""id"": ""ef3cbc64-b837-412f-ac1d-282d19899d22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice1"",
                    ""type"": ""Button"",
                    ""id"": ""e0bf2d38-c8b3-465a-951c-207437ef030e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice2"",
                    ""type"": ""Button"",
                    ""id"": ""85a5b242-e338-44bf-981d-ca88938dae7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice3"",
                    ""type"": ""Button"",
                    ""id"": ""c08fc8d2-359e-4cc2-ab97-6025c24a3b43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice4"",
                    ""type"": ""Button"",
                    ""id"": ""a16b1890-b029-438f-a688-1ab120b6e895"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice5"",
                    ""type"": ""Button"",
                    ""id"": ""527525e4-d38a-4bbf-b352-fc3b696ddc00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dice6"",
                    ""type"": ""Button"",
                    ""id"": ""83122141-2a7f-4d4b-b1f3-15b539219185"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""4aa4b832-1d7e-475a-9f2f-2c8f39d21ac7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b0636954-650a-41bc-a2e4-91d912ee4f4f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e400c33c-b126-42c7-9590-6cc2fb4e64b7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2328aabf-63ba-4f77-9b47-171bd6e0dc09"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d09da229-544d-42c2-83c5-9c65296ce1eb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""f923cc22-c905-43db-8250-c21017b9d142"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""51b0e2b2-99ef-4fa6-9683-3f8001ee9335"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6acb3d8d-4502-4beb-9d85-673f3149fc8a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0d6ea817-a3d2-4b67-8ad8-cb69c10b0097"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3b0dbe02-837d-417c-845e-731849e75a03"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8e42b6cf-986c-4406-b45f-bc1c5f7a4006"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a15cd64-de3f-431c-acd6-8d1b765fce8d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63560f35-62fa-4567-8b93-db837590bcf7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fce3890b-66d8-4a75-8174-7ed467c6a8cc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be55956d-6c91-488c-aeb8-1142ea0406de"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shockwave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f0ea8ee-f163-4ae1-892f-2e4e3d088c2a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""421c8ad3-4528-4144-87d1-7e3dc9415c3a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abcb4720-4c9f-4c70-b292-ee87d1599c1c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""213469db-8b50-4543-922e-08e6d7fa7048"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52ec9a00-f0c4-4ff5-9c6a-dd17548169e7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70efbc8f-f78a-465b-8148-e81410c5616a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f4b8b90-19c4-4403-b145-543f8cba6e83"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dice6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_MousePosition = m_Player.FindAction("Mouse Position", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_Shield = m_Player.FindAction("Shield", throwIfNotFound: true);
        m_Player_Shockwave = m_Player.FindAction("Shockwave", throwIfNotFound: true);
        m_Player_Fireball = m_Player.FindAction("Fireball", throwIfNotFound: true);
        m_Player_Dice1 = m_Player.FindAction("Dice1", throwIfNotFound: true);
        m_Player_Dice2 = m_Player.FindAction("Dice2", throwIfNotFound: true);
        m_Player_Dice3 = m_Player.FindAction("Dice3", throwIfNotFound: true);
        m_Player_Dice4 = m_Player.FindAction("Dice4", throwIfNotFound: true);
        m_Player_Dice5 = m_Player.FindAction("Dice5", throwIfNotFound: true);
        m_Player_Dice6 = m_Player.FindAction("Dice6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_MousePosition;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_Shield;
    private readonly InputAction m_Player_Shockwave;
    private readonly InputAction m_Player_Fireball;
    private readonly InputAction m_Player_Dice1;
    private readonly InputAction m_Player_Dice2;
    private readonly InputAction m_Player_Dice3;
    private readonly InputAction m_Player_Dice4;
    private readonly InputAction m_Player_Dice5;
    private readonly InputAction m_Player_Dice6;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @MousePosition => m_Wrapper.m_Player_MousePosition;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @Shield => m_Wrapper.m_Player_Shield;
        public InputAction @Shockwave => m_Wrapper.m_Player_Shockwave;
        public InputAction @Fireball => m_Wrapper.m_Player_Fireball;
        public InputAction @Dice1 => m_Wrapper.m_Player_Dice1;
        public InputAction @Dice2 => m_Wrapper.m_Player_Dice2;
        public InputAction @Dice3 => m_Wrapper.m_Player_Dice3;
        public InputAction @Dice4 => m_Wrapper.m_Player_Dice4;
        public InputAction @Dice5 => m_Wrapper.m_Player_Dice5;
        public InputAction @Dice6 => m_Wrapper.m_Player_Dice6;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @MousePosition.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousePosition;
                @Dash.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Shield.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Shield.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Shield.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Shockwave.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShockwave;
                @Shockwave.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShockwave;
                @Shockwave.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShockwave;
                @Fireball.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireball;
                @Fireball.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireball;
                @Fireball.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFireball;
                @Dice1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice1;
                @Dice1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice1;
                @Dice1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice1;
                @Dice2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice2;
                @Dice2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice2;
                @Dice2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice2;
                @Dice3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice3;
                @Dice3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice3;
                @Dice3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice3;
                @Dice4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice4;
                @Dice4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice4;
                @Dice4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice4;
                @Dice5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice5;
                @Dice5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice5;
                @Dice5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice5;
                @Dice6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice6;
                @Dice6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice6;
                @Dice6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDice6;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Shield.started += instance.OnShield;
                @Shield.performed += instance.OnShield;
                @Shield.canceled += instance.OnShield;
                @Shockwave.started += instance.OnShockwave;
                @Shockwave.performed += instance.OnShockwave;
                @Shockwave.canceled += instance.OnShockwave;
                @Fireball.started += instance.OnFireball;
                @Fireball.performed += instance.OnFireball;
                @Fireball.canceled += instance.OnFireball;
                @Dice1.started += instance.OnDice1;
                @Dice1.performed += instance.OnDice1;
                @Dice1.canceled += instance.OnDice1;
                @Dice2.started += instance.OnDice2;
                @Dice2.performed += instance.OnDice2;
                @Dice2.canceled += instance.OnDice2;
                @Dice3.started += instance.OnDice3;
                @Dice3.performed += instance.OnDice3;
                @Dice3.canceled += instance.OnDice3;
                @Dice4.started += instance.OnDice4;
                @Dice4.performed += instance.OnDice4;
                @Dice4.canceled += instance.OnDice4;
                @Dice5.started += instance.OnDice5;
                @Dice5.performed += instance.OnDice5;
                @Dice5.canceled += instance.OnDice5;
                @Dice6.started += instance.OnDice6;
                @Dice6.performed += instance.OnDice6;
                @Dice6.canceled += instance.OnDice6;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnShield(InputAction.CallbackContext context);
        void OnShockwave(InputAction.CallbackContext context);
        void OnFireball(InputAction.CallbackContext context);
        void OnDice1(InputAction.CallbackContext context);
        void OnDice2(InputAction.CallbackContext context);
        void OnDice3(InputAction.CallbackContext context);
        void OnDice4(InputAction.CallbackContext context);
        void OnDice5(InputAction.CallbackContext context);
        void OnDice6(InputAction.CallbackContext context);
    }
}
